"""A data processing API built with FastAPI, Pandas and NumPy.

    POST /load_data          read the CSV into a DataFrame
    GET  /describe_data      pandas describe()
    GET  /filter_data        filter rows on a condition
    GET  /columns            per-column types and null counts
    GET  /stats/{column}     NumPy statistics for one numeric column
    GET  /group_by           group and aggregate
    GET  /correlation        Pearson matrix from numpy.corrcoef
    GET  /health             whether anything is loaded

Swagger UI is at /docs and ReDoc at /redoc, both generated by FastAPI from the
type hints and the models in schemas.py.
"""
from __future__ import annotations

import os
from typing import Literal

from fastapi import FastAPI, HTTPException, Path, Query, Request
from fastapi.responses import JSONResponse

from . import processing as proc
from . import state
from .schemas import (ColumnsResult, CorrelationResult, DescribeResult, Error,
                      FilterResult, GroupByResult, Health, LoadResult,
                      StatsResult)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA_FILE = os.environ.get("DATA_FILE", os.path.join(ROOT, "data", "iris.csv"))

DESCRIPTION = """
A small API for poking at a tabular dataset over HTTP.

The dataset ships with the project: the **Iris** measurements, 150 rows and five
columns. `POST /load_data` reads it into a Pandas DataFrame that is kept in
memory; every other endpoint works on that DataFrame and returns **409** if it
has not been loaded yet.

Pandas does the loading, describing, filtering and grouping. NumPy does the
statistics in `/stats/{column}` and the correlation matrix.
"""

TAGS = [
    {"name": "data", "description": "Loading and inspecting the dataset."},
    {"name": "analysis", "description": "Statistics over the loaded data."},
    {"name": "service", "description": "Service status."},
]

ERRORS = {
    409: {"model": Error, "description": "No dataset is loaded."},
    404: {"model": Error, "description": "No such column."},
    400: {"model": Error, "description": "The request could not be applied."},
}

app = FastAPI(
    title="Data Processing API",
    version="1.0.0",
    description=DESCRIPTION,
    openapi_tags=TAGS,
    contact={"name": "John Michael Bilbao"},
)


# --------------------------------------------------------------- error shaping
def fail(code: str, message: str, status: int) -> JSONResponse:
    return JSONResponse(status_code=status,
                        content={"error": code, "message": message})


@app.exception_handler(state.DataNotLoaded)
async def not_loaded(_request: Request, exc: state.DataNotLoaded):
    return fail("data_not_loaded", str(exc), 409)


@app.exception_handler(proc.ColumnError)
async def bad_column(_request: Request, exc: proc.ColumnError):
    # KeyError stringifies with quotes around it, so use the original message.
    return fail("column_error", exc.args[0], 404)


@app.exception_handler(proc.FilterError)
async def bad_filter(_request: Request, exc: proc.FilterError):
    return fail("filter_error", str(exc), 400)


@app.exception_handler(HTTPException)
async def http_error(_request: Request, exc: HTTPException):
    return fail("error", exc.detail, exc.status_code)


# -------------------------------------------------------------------- service
@app.get("/health", response_model=Health, tags=["service"],
         summary="Is the service up, and is anything loaded")
def health() -> Health:
    rows = len(state.frame()) if state.is_loaded() else None
    return Health(status="ok", data_loaded=state.is_loaded(), rows=rows)


# ----------------------------------------------------------------------- data
@app.post("/load_data", response_model=LoadResult, tags=["data"],
          summary="Load the dataset into a DataFrame",
          description="Reads the bundled CSV with `pandas.read_csv`, lowercases "
                      "the column names and keeps the DataFrame in memory. "
                      "Calling it again reloads from disk and discards any "
                      "previous copy.",
          responses={404: ERRORS[404]})
def load_data() -> LoadResult:
    if not os.path.exists(DATA_FILE):
        raise HTTPException(status_code=404,
                            detail=f"Data file not found: {DATA_FILE}")

    frame = proc.load_csv(DATA_FILE)
    dataset = state.store(frame, os.path.relpath(DATA_FILE, ROOT))

    return LoadResult(
        source=dataset.source,
        loaded_at=dataset.loaded_at,
        rows=int(frame.shape[0]),
        columns=int(frame.shape[1]),
        column_names=[str(c) for c in frame.columns],
        dtypes={str(c): str(dt) for c, dt in frame.dtypes.items()},
        memory_bytes=int(frame.memory_usage(deep=True).sum()),
        preview=proc.preview(frame),
    )


@app.get("/columns", response_model=ColumnsResult, tags=["data"],
         summary="The columns, their types and their null counts",
         responses={409: ERRORS[409]})
def columns() -> ColumnsResult:
    frame = state.frame()
    return ColumnsResult(rows=len(frame),
                         columns=proc.column_summary(frame))


@app.get("/describe_data", response_model=DescribeResult, tags=["data"],
         summary="Summary statistics from pandas describe()",
         description="`describe(include='all')`, so text columns get count, "
                     "unique, top and freq while numeric columns get the mean, "
                     "standard deviation and quartiles. Missing combinations "
                     "come back as null.",
         responses={409: ERRORS[409]})
def describe_data() -> DescribeResult:
    frame = state.frame()
    table = proc.describe(frame)
    first = next(iter(table.values()), {})
    return DescribeResult(rows=len(frame),
                          statistics=list(first.keys()),
                          describe=table)


@app.get("/filter_data", response_model=FilterResult, tags=["data"],
         summary="Filter rows on a condition",
         description="Builds a boolean mask and returns the rows that match. "
                     "The value arrives as text and is converted to a number "
                     "when the column is numeric, so `value=5` and `value=5.0` "
                     "behave the same on a float column.",
         responses={409: ERRORS[409], 404: ERRORS[404], 400: ERRORS[400]})
def filter_data(
    column: str = Query(description="Column to test.",
                        examples=["petal_length"]),
    op: Literal["eq", "ne", "gt", "gte", "lt", "lte", "contains"] = Query(
        "eq", description="Comparison to apply."),
    value: str = Query(description="Value to compare against.",
                       examples=["5.0"]),
    limit: int = Query(10, ge=1, le=150,
                       description="Most rows to return."),
) -> FilterResult:
    frame = state.frame()
    matched = proc.filter_rows(frame, column, op, value)
    head = matched.head(limit)
    return FilterResult(
        column=column, op=op, value=value,
        matched=int(len(matched)), total=int(len(frame)),
        returned=int(len(head)), limit=limit,
        rows=proc.records(head),
    )


# ------------------------------------------------------------------- analysis
@app.get("/stats/{column}", response_model=StatsResult, tags=["analysis"],
         summary="NumPy statistics for one numeric column",
         description="Mean, median, sample standard deviation, variance, "
                     "quartiles and the Tukey outlier fences, all computed with "
                     "NumPy on the column as a float array.",
         responses={409: ERRORS[409], 404: ERRORS[404]})
def stats(column: str = Path(description="A numeric column.",
                             examples=["petal_length"])) -> StatsResult:
    return StatsResult(**proc.numeric_stats(state.frame(), column))


@app.get("/group_by", response_model=GroupByResult, tags=["analysis"],
         summary="Group by one column and aggregate another",
         responses={409: ERRORS[409], 404: ERRORS[404], 400: ERRORS[400]})
def group_by(
    by: str = Query(description="Column to group on.", examples=["species"]),
    column: str = Query(description="Numeric column to aggregate.",
                        examples=["petal_length"]),
    agg: Literal["mean", "median", "sum", "min", "max", "std",
                 "count"] = Query("mean", description="Aggregation to apply."),
) -> GroupByResult:
    groups = proc.group_by(state.frame(), by, column, agg)
    return GroupByResult(by=by, column=column, agg=agg, groups=groups)


@app.get("/correlation", response_model=CorrelationResult, tags=["analysis"],
         summary="Pearson correlation between the numeric columns",
         description="`numpy.corrcoef` over the numeric columns. The diagonal is "
                     "1 by definition.",
         responses={409: ERRORS[409], 404: ERRORS[404]})
def correlation() -> CorrelationResult:
    return CorrelationResult(**proc.correlation(state.frame()))
